domain: omop.fi

migrationState:
  completed: true
  migrationPodEnabled: false

homebridge.enabled: false
ha.enabled: false
frigate.enabled: false

mariaDB:
  namespace: home-internal
  persistentVolume:
    storageClassName: "local-path"  # or "" if problem
    name: mariadb-retained-pv
    hostPath: /Users/yyy/Lab/home/data/temporary/mariadb
    storage: 10Gi
  envFromSecret: mariadb-credentials
  image:
    repository: mariadb
    tag: "12.0.2"
    pullPolicy: IfNotPresent
 
auth:
  replicas: 1
  enableMultiAuth: false
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: "v7.15.1-alpine"
    pullPolicy: IfNotPresent
  cookieDomain: .omop.fi
  cookieSecure: true
  emailDomain: "*"
  authDomain: auth.omop.fi
  envFromSecret: oauth2-proxy-credentials
  skipAuthRoutes:
    - "^/$"
    - "^/public/.*"
    - "^/api/public/.*"
    - "^/api/health$"
    - "^/docs$"
    - "^/openapi.json$"
    - "^/favicon.ico$"
    - "^/robots.txt$"

stirlingPdf:
  namespace: web
  replicas: 1
  image:
    repository: stirlingtools/stirling-pdf
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    host: pdf.omop.fi

restic:
  namespace: home-internal
  schedule: "15 17 * * *"
  timezone: "Europe/Helsinki"
  image:
    repository: restic/restic
    tag: latest
  resticRepository: "s3:s3.eu-central-003.backblazeb2.com/yyyRestic"
  hostPathConfig: /Users/yyy/Lab/home/config
