apiVersion: v1
kind: Service
metadata:
  name: pdf-svc
  namespace: {{ .Values.stirlingPdf.namespace }}
  labels:
    app: pdf
spec:
  type: ClusterIP
  selector:
    app: pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080