events { }

http {
    server {
        listen 80;
        server_name h.yan.fi pi.yan.fi;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 404;
        }
    }
}
