version: '3'

includes:
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra
  play: 
    taskfile: ./apps/py-play/Taskfile.yaml
    dir: ./apps/py-play
  poller: 
    taskfile: ./apps/py-poller/Taskfile.yaml
    dir: ./apps/py-poller

tasks:
  build-images-locally:
    desc: "Build play and poller local images"
    cmds:
      - task: play:build-local-image
      - task: poller:build-local-image

  deploy-core:
    desc: Deploy the core helm chart
    cmds:
      - task: infra:deploy-core
