version: '3'

includes:
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra
  play: 
    taskfile: ./apps/py-play/Taskfile.yaml
    dir: ./apps/py-play
  poller: 
    taskfile: ./apps/bash-poller/Taskfile.yaml
    dir: ./apps/bash-poller

tasks:
  build-play-image:
    desc: "Build play local image"
    cmds:
      - docker build -t play:local -f apps/py-play/Dockerfile .

  build-all-images:
    desc: "Build all local images"
    cmds:
      - task: build-play-image
      - task: poller:build-local-image
      - docker tag play:local yyyaaan/play:alpha1
      - docker push yyyaaan/play:alpha1
      - docker tag poller:local yyyaaan/poller:alpha1
      - docker push yyyaaan/poller:alpha1

  deploy-play:
    desc: Deploy the play helm chart - use gitops instead
    cmds:
      - task: play:deploy

  lint-helm:
    desc: lint and check helm charts across projects
    cmds:
      - helm lint ./apps/bash-poller/helm-chart
      - helm lint ./apps/py-play/helm-chart
      - helm lint ./infra/helm-chart
      - helm install test-only ./infra/helm-chart --dry-run=client --debug > zzz.yaml
  
  bootstrap-test:
    desc: bootstrap production gitops stacks (infra to be installed with ArgoCD)
    cmds:
      - task: infra:bootstrap
        vars: { ENV: "test" }

  bootstrap:
    desc: bootstrap production gitops stacks (infra to be installed with ArgoCD)
    cmds:
      - task: infra:bootstrap
        vars: { ENV: "prod" }
