version: '3'

includes:
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra
  play: 
    taskfile: ./apps/py-play/Taskfile.yaml
    dir: ./apps/py-play
  poller: 
    taskfile: ./apps/py-poller/Taskfile.yaml
    dir: ./apps/py-poller

tasks:
  build-play-image:
    desc: "Build play local image"
    cmds:
      - docker build -t py-play -f apps/py-play/Dockerfile .

  build-all-images:
    desc: "Build all local images"
    cmds:
      - task: build-play-image
      - task: poller:build-local-image

  deploy-core:
    desc: Deploy the core helm chart
    cmds:
      - task: infra:deploy-core
