NAME: test-only
LAST DEPLOYED: Fri Apr 17 13:40:25 2026
NAMESPACE: default
STATUS: pending-install
REVISION: 1
DESCRIPTION: Dry run complete
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
auth:
  authDomain: auth.yan.fi
  cookieDomain: .yan.fi
  cookieSecure: true
  emailDomain: '*'
  enableMultiAuth: false
  envFromSecret: oauth2-proxy-credentials
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.15.1-alpine
  replicas: 1
  skipAuthRoutes:
  - ^/$
  - ^/public/.*
  - ^/docs$
  - ^/openapi.json$
  - ^/favicon.ico$
  - ^/api/health$
  - ^/robots.txt$
certManager:
  issuerName: letsencrypt-prod
domain: yan.fi
frigate:
  cacheSize: 900Mi
  enabled: true
  envFromSecret: frigate-credentials
  hostPathConfig: /mnt/kingston/home/config/frigate
  hostPathMedia: /mnt/kingston/share/media/frigate
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/blakeblackshear/frigate
    tag: 0.17.0
  ingress:
    host: frigate.yan.fi
  namespace: home-internal
  privileged: true
  replicas: 1
  shmSize: 384Mi
ha:
  enableBluetooth: true
  enabled: true
  envFromSecretList:
  - tz-config
  hostPathConfig: /mnt/kingston/home/config/ha
  hostPathMedia: /mnt/kingston/share/media
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/home-assistant/home-assistant
    tag: 2026.3.4
  ingress:
    host: h.yan.fi
  namespace: home-internal
  replicas: 1
homebridge:
  enabled: true
  hostPathConfig: /mnt/kingston/home/config/hb
  image:
    pullPolicy: IfNotPresent
    repository: homebridge/homebridge
    tag: "2026-02-25"
  ingress:
    enabled: true
    host: homebridge.yan.fi
  namespace: home-internal
  replicas: 1
mariaDB:
  envFromSecret: mariadb-credentials
  image:
    pullPolicy: IfNotPresent
    repository: mariadb
    tag: 12.0.2
  namespace: home-internal
  persistentVolume:
    hostPath: /mnt/kingston/home/data/volume/mariadb
    name: mariadb-retained-pv
    storage: 10Gi
    storageClassName: local-path
migrationState:
  completed: true
  migrationPodEnabled: false
mqtt:
  enabled: true
  hostPathData: /mnt/kingston/home/config/mqtt/config
  image:
    pullPolicy: IfNotPresent
    repository: eclipse-mosquitto
    tag: 2.1-alpine
  namespace: home-internal
restic:
  hostPathConfig: /mnt/kingston/home/config
  image:
    repository: restic/restic
    tag: latest
  namespace: home-internal
  resticRepository: s3:s3.eu-central-003.backblazeb2.com/yyyRestic
  schedule: 15 17 * * *
  timezone: Europe/Helsinki
stirlingPdf:
  image:
    pullPolicy: IfNotPresent
    repository: stirlingtools/stirling-pdf
    tag: latest
  ingress:
    host: pdf.yan.fi
  namespace: web
  replicas: 0

HOOKS:
MANIFEST:
---
# Source: yan-fi-server/templates/mariadb/pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-retained-pv
  # PV is cluster-wide resource, so no namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/kingston/home/data/volume/mariadb
---
# Source: yan-fi-server/templates/mariadb/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: home-internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: mariadb-retained-pv
---
# Source: yan-fi-server/templates/frigate/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frigate-service
  namespace: home-internal
  labels:
    app.kubernetes.io/name: frigate
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frigate
  ports:
  - name: web-ui
    port: 8971
    targetPort: 8971
    protocol: TCP
  - name: api
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: rtsp
    port: 8554
    targetPort: 8554
    protocol: TCP
  - name: webrtc-tcp
    port: 8555
    targetPort: 8555
    protocol: TCP
  - name: webrtc-udp
    port: 8555
    targetPort: 8555
    protocol: UDP
---
# Source: yan-fi-server/templates/home-assistant/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ha-service
  namespace: home-internal
  labels:
    app.kubernetes.io/name: ha
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ha
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
---
# Source: yan-fi-server/templates/homebridge/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: homebridge-service
  namespace: home-internal
  labels:
    app.kubernetes.io/name: homebridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: homebridge
  ports:
  - port: 8581
    targetPort: 8581
    protocol: TCP
    name: http
---
# Source: yan-fi-server/templates/mariadb/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: home-internal
  labels:
    app.kubernetes.io/name: mariadb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
---
# Source: yan-fi-server/templates/mqtt/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: home-internal
  labels:
    app.kubernetes.io/name: mqtt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt
  ports:
  - name: mqtt-tcp
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mqtt-ws
    port: 9001
    targetPort: 9001
    protocol: TCP
---
# Source: yan-fi-server/templates/oauth2-proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  ports:
  - port: 4180
    targetPort: 4180
  selector:
    app: oauth2-proxy
---
# Source: yan-fi-server/templates/stirling-pdf/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdf-svc
  namespace: web
  labels:
    app: pdf
spec:
  type: ClusterIP
  selector:
    app: pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# Source: yan-fi-server/templates/frigate/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: home-internal
  labels:
    app.kubernetes.io/name: frigate
spec:
  replicas: 1
  strategy:
    type: Recreate # Prevents volume locking issues with HostPaths
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
    spec:
      containers:
      - name: frigate
        image: "ghcr.io/blakeblackshear/frigate:0.17.0"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: frigate-credentials
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2500m"
            memory: "5Gi"
        ports:
        - containerPort: 8971
          name: web-ui
        - containerPort: 5000
          name: api
        - containerPort: 8554
          name: rtsp
        - containerPort: 8555
          protocol: TCP
          name: webrtc-tcp
        - containerPort: 8555
          protocol: UDP
          name: webrtc-udp
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media/frigate
        - name: dshm
          mountPath: /dev/shm
        - name: cache
          mountPath: /tmp/cache
      volumes:
      - name: config
        hostPath:
          path: /mnt/kingston/home/config/frigate
          type: DirectoryOrCreate
      - name: media
        hostPath:
          path: /mnt/kingston/share/media/frigate
          type: DirectoryOrCreate
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 384Mi
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 900Mi
---
# Source: yan-fi-server/templates/home-assistant/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha
  namespace: home-internal
  labels:
    app.kubernetes.io/name: ha
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ha
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ha
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ha
        image: "ghcr.io/home-assistant/home-assistant:2026.3.4"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        envFrom:
          - secretRef:
              name: "tz-config"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "1500m"
            memory: "2000Mi"
        ports:
        - containerPort: 8123
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: dbus
          mountPath: /run/dbus
          readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /mnt/kingston/home/config/ha
          type: Directory
      - name: media
        hostPath:
          path: /mnt/kingston/share/media
          type: Directory
      - name: dbus
        hostPath:
          path: /run/dbus
          type: Directory # Expects the host to already have this
---
# Source: yan-fi-server/templates/homebridge/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: home-internal
  labels:
    app.kubernetes.io/name: homebridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homebridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homebridge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: "homebridge/homebridge:2026-02-25"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8581
          name: http
        volumeMounts:
        - name: config
          mountPath: /homebridge
      volumes:
      - name: config
        hostPath:
          path: /mnt/kingston/home/config/hb
          type: Directory
---
# Source: yan-fi-server/templates/mariadb/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: home-internal
  labels:
    app.kubernetes.io/name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
    spec:
      containers:
      - name: mariadb
        image: "mariadb:12.0.2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        args:
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
        envFrom:
        - secretRef:
            name: mariadb-credentials
        resources:
          requests:
            cpu: "10m"
            memory: "500Mi"
          limits:
            cpu: "900m"
            memory: "2000Mi"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-data
---
# Source: yan-fi-server/templates/mqtt/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: home-internal
  labels:
    app.kubernetes.io/name: mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt
    spec:
      containers:
      - name: mqtt
        image: "eclipse-mosquitto:2.1-alpine"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "300m"
            memory: "300Mi"
        ports:
        - containerPort: 1883
          name: mqtt-tcp
        - containerPort: 9001
          name: mqtt-ws
        volumeMounts:
        - name: mqtt-data
          mountPath: /mosquitto/config
      volumes:
      - name: mqtt-data
        hostPath:
          path: /mnt/kingston/home/config/mqtt/config
          type: Directory
---
# Source: yan-fi-server/templates/oauth2-proxy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.1-alpine
        args:
          - "--provider=google"
          - "--upstream=file:///dev/null"
          - "--http-address=0.0.0.0:4180"
          - "--reverse-proxy=true"
          - "--redirect-url=https://auth.yan.fi/oauth2/callback"
          - "--whitelist-domain=.yan.fi"
          - "--cookie-domain=.yan.fi"
          - "--cookie-secure=true"
          - "--email-domain=*"
          - "--skip-auth-route=^/$"
          - "--skip-auth-route=^/public/.*"
          - "--skip-auth-route=^/docs$"
          - "--skip-auth-route=^/openapi.json$"
          - "--skip-auth-route=^/favicon.ico$"
          - "--skip-auth-route=^/api/health$"
          - "--skip-auth-route=^/robots.txt$"
        envFrom:
        - secretRef:
            name: oauth2-proxy-credentials
        ports:
        - containerPort: 4180
---
# Source: yan-fi-server/templates/stirling-pdf/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf
  namespace: web
  labels:
    app.kubernetes.io/name: pdf
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pdf
  template:
    metadata:
      labels:
        app: pdf
    spec:
      containers:
      - name: pdf
        image: stirlingtools/stirling-pdf:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SECURITY_ENABLELOGIN
            value: "false"    # middleware handles authentication
        resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "2000m"
              memory: "3Gi"
---
# Source: yan-fi-server/templates/cronjobs/cronjob-restic.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic
  namespace: home-internal
  labels:
    app.kubernetes.io/name: restic
    app.kubernetes.io/component: backup
spec:
  schedule: "15 17 * * *"
  timeZone: "Europe/Helsinki"
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: mariadb-dump
            image: mariadb:12.0.2
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: 
            - "mariadb-dump -h mariadb-service -u root -p$DB_PASSWORD --all-databases > /db-dump/dump.sql"
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: MARIADB_ROOT_PASSWORD
            volumeMounts:
            - name: dump-volume
              mountPath: /db-dump
          containers:
          - name: restic
            image: restic/restic:latest
            args:
            - -r
            - "s3:s3.eu-central-003.backblazeb2.com/yyyRestic"
            - backup
            - /home-configs
            - /db-dump
            - --exclude="backup"
            - --exclude="backups"
            securityContext:
              runAsUser: 0 
            envFrom:
            - secretRef:
                name: restic-credentials
            volumeMounts:
            - name: config-folder
              mountPath: /home-configs
              readOnly: true
            - name: dump-volume
              mountPath: /db-dump
              readOnly: true
          volumes:
          - name: config-folder
            hostPath:
              path: /mnt/kingston/home/config
              type: Directory
          - name: dump-volume
            emptyDir: {}
---
# Source: yan-fi-server/templates/frigate/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate-ingress
  namespace: home-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - frigate.yan.fi
    secretName: frigate-tls-cert
  rules:
  - host: frigate.yan.fi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frigate-service
            port:
              number: 8971
---
# Source: yan-fi-server/templates/home-assistant/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress
  namespace: home-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - h.yan.fi
    secretName: ha-tls-cert
  rules:
  - host: h.yan.fi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ha-service
            port:
              number: 8123
---
# Source: yan-fi-server/templates/homebridge/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge-ingress
  namespace: home-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - homebridge.yan.fi
    secretName: homebridge-tls-cert
  rules:
  - host: homebridge.yan.fi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homebridge-service
            port:
              number: 8581
---
# Source: yan-fi-server/templates/oauth2-proxy/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: auth
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - auth.yan.fi
    secretName: auth-tls-cert
  rules:
  - host: auth.yan.fi
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
---
# Source: yan-fi-server/templates/stirling-pdf/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-ingress
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: auth-oauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - pdf.yan.fi
    secretName: pdf-tls-cert
  rules:
  - host: pdf.yan.fi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdf-svc
            port:
              number: 80
---
# Source: yan-fi-server/templates/mariadb/pod-migration-only.yaml
# only for migration
---
# Source: yan-fi-server/templates/mariadb/pvc.yaml
# manual PV and PVC for MariaDB, using specified path (but not bind mount)
---
# Source: yan-fi-server/templates/oauth2-proxy/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth
  namespace: auth
spec:
  forwardAuth:
    address: http://oauth2-proxy.auth.svc.cluster.local:4180/oauth2/auth
    # address: https://auth.yan.fi/oauth2/auth
    trustForwardHeader: true
    # the following may be deleted to preserve all headers from oauth2-proxy
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization

