apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: {{ .Values.mqtt.namespace }}
  labels:
    app.kubernetes.io/name: mqtt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt
  ports:
  - name: mqtt-tcp
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mqtt-ws
    port: 9001
    targetPort: 9001
    protocol: TCP