apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: {{ .Values.frigate.namespace }}
  labels:
    app.kubernetes.io/name: frigate
spec:
  replicas: {{ .Values.frigate.replicas }}
  strategy:
    type: Recreate # Prevents volume locking issues with HostPaths
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
    spec:
      containers:
      - name: frigate
        image: "{{ .Values.frigate.image.repository }}:{{ .Values.frigate.image.tag }}"
        imagePullPolicy: {{ .Values.frigate.image.pullPolicy }}
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: {{ .Values.frigate.envFromSecret }}
        ports:
        - containerPort: 8971
          name: web-ui
        - containerPort: 5000
          name: api
        - containerPort: 8554
          name: rtsp
        - containerPort: 8555
          protocol: TCP
          name: webrtc-tcp
        - containerPort: 8555
          protocol: UDP
          name: webrtc-udp
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media/frigate
        - name: dshm
          mountPath: /dev/shm
        - name: cache
          mountPath: /tmp/cache
      volumes:
      - name: config
        hostPath:
          path: {{ .Values.frigate.hostPathConfig }}
          type: DirectoryOrCreate
      - name: media
        hostPath:
          path: {{ .Values.frigate.hostPathMedia }}
          type: DirectoryOrCreate
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.frigate.shmSize }}
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.frigate.cacheSize }}