namespace: web
authMiddleware:
  enabled: true
  name: auth-oauth@kubernetescrd
image:
  repository: ghcr.io/yyyaaan/core/web
  tag: "sha-723b8d2"
  pullPolicy: IfNotPresent
envFromSecretList:
  - tz-config
memDiskSize: 10Mi
service:
  targetPort: 8001
ingress:
  host: yan.fi
  additionalHosts:
    - staging.yan.fi
    - omop.fi
