namespace: web
authMiddleware:
  enabled: true
  name: auth-oauth@kubernetescrd
image:
  repository: ghcr.io/yyyaaan/core/web
  tag: "sha-0efd7ec"
  pullPolicy: IfNotPresent
envFromSecretList:
  - tz-config
memDiskSize: 10Mi
service:
  targetPort: 8001
ingress:
  host: staging.yan.fi
