version: '3'

vars:
  ENV: '{{.ENV | default "prod"}}'

tasks:
  # --- INFRASTRUCTURE of ARGOCD, GITOPS ONLY ---

  _apply-secret:  # internal helper only
    internal: true
    label: "Applying secret: {{.NAME}} in {{.NS}}"
    cmds:
      - kubectl create secret generic {{.NAME}} -n {{.NS}} --from-env-file={{.FILE}} --dry-run=client -o yaml | kubectl apply -f -
    status:
      - test ! -f {{.FILE}}
  
  setup-namespaces:  # deps to secrets
    internal: true
    cmds:
      - for: [argocd, auth, cert-manager, cloudflared, headlamp, home-internal, traefik, web]
        cmd: kubectl create namespace {{.ITEM}} --dry-run=client -o yaml | kubectl apply -f -

  # task infra:secrets ENV=test
  secrets:
    desc: "Create all secrets from env files (Idempotent)"
    deps: [setup-namespaces]
    vars:
      SUFFIX: '{{if eq .ENV "test"}}.test{{else}}{{end}}'
      ITEMS:
        - { NAME: oidc-secret,              NS: argocd,        FILE: ./credentials/oidc.env }
        - { NAME: cloudflare-api-token,     NS: cert-manager,  FILE: ./credentials/cloudflare.env }
        - { NAME: cloudflared-token,        NS: cloudflared,   FILE: "./credentials/cloudflare{{.SUFFIX}}.env" }
        - { NAME: oidc-secret,              NS: headlamp,      FILE: ./credentials/oidc.env }
        - { NAME: oauth2-proxy-credentials, NS: auth,          FILE: ./credentials/oauth.env }
        - { NAME: email-credentials,        NS: web,           FILE: ./credentials/email.env }
        - { NAME: tz-config,                NS: web,           FILE: ./credentials/tz.env }
        - { NAME: tz-config,                NS: home-internal, FILE: ./credentials/tz.env }
        - { NAME: frigate-credentials,      NS: home-internal, FILE: ./credentials/frigate.env }
        - { NAME: mariadb-credentials,      NS: home-internal, FILE: ./credentials/db.env }
        - { NAME: poller-credentials,       NS: home-internal, FILE: ./credentials/poll.env }
        - { NAME: restic-credentials,       NS: home-internal, FILE: ./credentials/restic.env }
    cmds:
      - for: { var: ITEMS }
        task: _apply-secret
        vars:
          NAME: '{{.ITEM.NAME}}'
          NS: '{{.ITEM.NS}}'
          FILE: '{{.ITEM.FILE}}'

  argocd:
    desc: "Install Argo CD"
    cmds: 
      - kubectl label secret oidc-secret --namespace argocd "app.kubernetes.io/part-of=argocd"
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - helm upgrade --install argocd argo/argo-cd --namespace argocd -f bootstrap/values/argocd.yaml

  # --- MONITORING OPS ---

  argocd:login:
    desc: "Open ArgoCD UI, port-forward, and print credentials"
    cmds:
      - |
        echo "🔑 Waiting for ArgoCD server to be ready, and fetching admin password for local login"
        kubectl wait --for=condition=Available deployment/argocd-server -n argocd --timeout=300s
        PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
        
        echo "----------------------------------------"
        echo "👤 Username: admin"
        echo "🔐 Password: $PASSWORD"
        echo "----------------------------------------"
        
        echo "🌐 Opening browser to https://localhost:9080..."
        (sleep 2 && (open http://localhost:9080 || xdg-open http://localhost:9080 || start https://localhost:9080) &> /dev/null) &
        
        echo "🚀 Starting port-forward (Press Ctrl+C to stop)..."
        kubectl port-forward svc/argocd-server -n argocd 9080:80

  headlamp:login:
    desc: "Open headlamp and obtain token]"
    cmds:
      - |
        echo "🔑 Fetching cluster token for headlamp"
        TOKEN=$(kubectl create token headlamp -n headlamp)
        HOST=$(kubectl get ingress headlamp -n headlamp -o jsonpath='{.spec.rules[0].host}')
        echo "🔐 Token: $TOKEN"
        open https://$HOST

  # --- DEPLOYMENT / GitOps with ArgoCD recommended ---

  deprecated-helm-deploy-core-test:
    desc: "Deploy main application stack via Helm"
    deps: [secrets]
    cmds:
      - helm upgrade --install core-infra ./helm-chart -f ./helm-chart/values-test.yaml
  
  # --- GitOps ---

  bootstrap:
    desc: "Bootstrap Cluster and ArgoCD GitOps Stack - continue with ArgoCD"
    vars:
      FOLDER: '{{if eq .ENV "test"}}test-domain{{else}}yan-fi{{end}}'
    cmds:
      - task: secrets
        vars:
            ENV: '{{.ENV}}'
      - task: argocd
      - kubectl apply -f gitops-config/bootstrap-cluster
      - kubectl apply -f gitops-config/{{.FOLDER}}
      - task: argocd:login

# task infra:gitops ENV=test