version: '3'

vars:
  CERT_MANAGER_VERSION: v1.14.0
  DOMAIN: omop.fi

tasks:
  # --- INFRASTRUCTURE (BOOTSTRAP) ---

  traefik:
    desc: "OrbStack only: Install Traefik Ingress Controller on different ports"
    cmds:
      - kubectl create namespace traefik --dry-run=client -o yaml | kubectl apply -f - 
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo update
      - helm upgrade --install traefik traefik/traefik --namespace traefik --set ports.web.exposedPort=8080 --set ports.websecure.exposedPort=8443

  cert-manager:
    desc: "Install Cert-Manager and Cloudflare Issuer"
    cmds:
      - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{.CERT_MANAGER_VERSION}}/cert-manager.yaml
      - kubectl wait --for=condition=Available deployment --all -n cert-manager --timeout=60s
      - kubectl create secret generic cloudflare-api-token --namespace cert-manager --from-env-file=./credentials/cloudflare.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f bootstrap/k8s-cloudflare-cert-issuer.yaml

  cloudflare-tunnel:
    desc: "Setup Cloudflare Tunnel"
    cmds:
      - kubectl create namespace cloudflared --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f bootstrap/k8s-cloudflared-tunnel-deployment.yaml

  https-middleware:
    desc: "[dependency] Create Traefik Middleware to force HTTPS for ArgoCD and Headlamp callback"
    cmds:
      - kubectl apply -f bootstrap/k8s-force-https-middleware.yaml

  argocd:
    desc: "Install Argo CD"
    deps: [https-middleware]
    cmds: 
    - |
      kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
      kubectl create secret generic oidc-secret --namespace argocd --from-env-file=./credentials/oidc.env --dry-run=client -o yaml | kubectl apply -f -
      kubectl label secret oidc-secret --namespace argocd "app.kubernetes.io/part-of=argocd"
      helm repo add argo https://argoproj.github.io/argo-helm
      helm repo update
      helm upgrade --install argocd argo/argo-cd --namespace argocd -f bootstrap/helm-values-argocd.yaml

  headlamp:
    desc: "Install Headlamp Dashboard"
    deps: [https-middleware]
    cmds:
      - kubectl create namespace headlamp --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic oidc-secret -n headlamp --from-env-file=./credentials/oidc.env --dry-run=client -o yaml | kubectl apply -f -
      - helm repo add headlamp https://kubernetes-sigs.github.io/headlamp/
      - helm repo update
      - helm upgrade --install headlamp headlamp/headlamp --namespace headlamp -f bootstrap/helm-values-headlamp.yaml
      - kubectl apply -f bootstrap/k8s-rbac-oidc-admin.yaml

  # --- NAMESPACES & SECRETS [excluding bootstrap ones] ---

  setup-namespaces:
    internal: true
    cmds:
      - for: [auth, home-internal, web]
        cmd: kubectl create namespace {{.ITEM}} --dry-run=client -o yaml | kubectl apply -f -

  secrets:
    desc: "Create all secrets from env files (Idempotent)"
    deps: [setup-namespaces]
    cmds:
      # Pattern: Create secret only if it changed/doesn't exist using dry-run + apply
      - kubectl create secret generic oauth2-proxy-credentials -n auth --from-env-file=./credentials/oauth.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic email-credentials -n web --from-env-file=./credentials/email.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic tz-config -n web --from-env-file=./credentials/tz.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic tz-config -n home-internal --from-env-file=./credentials/tz.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic frigate-credentials -n home-internal --from-env-file=./credentials/frigate.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic mariadb-credentials -n home-internal --from-env-file=./credentials/db.env --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic poller-credentials -n home-internal --from-env-file=./credentials/poll.env --dry-run=client -o yaml | kubectl apply -f -

  # --- MONITORING ---
  job-logs:
    desc: "Stream logs of all jobs in web namespace"
    cmds:
      - kubectl logs -l app.kubernetes.io/component=elenia

  token:
    desc: "Obtain cluster token for headlamp (RBAC recommended though)"
    cmds:
      - kubectl create token headlamp -n headlamp

  # --- DEPLOYMENT: choose only one! either helm or gitops ---

  helm-deploy-core-test:
    desc: "Deploy main application stack via Helm"
    deps: [secrets]
    cmds:
      - helm upgrade --install omop-fi ./helm-chart -f ./helm-chart/values-test.yaml
  
  # --- GitOps ---

  gitops-test:
    desc: "Register Apps and Repos for ArgoCD"
    cmds:
      - kubectl apply -f gitops-config/test-domain

  gitops:
    desc: "Register Apps and Repos for ArgoCD"
    cmds:
      - kubectl apply -f gitops-config/yan-fi


  # --- ALL-IN-ONE ---

  bootstrap:
    desc: "Full cluster bootstrap, without MariaDB migration"
    cmds:
      - task: traefik
      - task: cert-manager
      - task: cloudflare-tunnel
      - task: argocd
      - task: headlamp
      - task: secrets
      - task: gitops
