apiVersion: apps/v1
kind: Deployment
metadata:
  name: play
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: play
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      labels:
        app: play
    spec:
      containers:
      - name: play
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        {{- range .Values.envFromSecretList }}
          - secretRef:
              name: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limit:
            cpu: "500m"
            memory: "800Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /mnt
        - name: mem-disk-volume
          mountPath: /tmp/cache
      volumes:
      - name: data-volume
        hostPath:
          path: {{ .Values.hostPathForData }}
          type: DirectoryOrCreate
      - name: mem-disk-volume
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.memDiskSize }}