apiVersion: v1
kind: Service
metadata:
  name: play-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: play
spec:
  type: ClusterIP
  selector:
    app: play
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort }}