apiVersion: v1
kind: Service
metadata:
  name: play-svc
  labels:
    app: play
spec:
  type: ClusterIP
  selector:
    app: play
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.play.service.targetPort }}