FROM python:3.12-slim

# Create a non-root user and group
RUN groupadd -r appgroup && useradd -r -g appgroup appuser

# deps
RUN apt update && apt install -y  mosquitto-clients
RUN pip install pytest-playwright fastapi uvicorn
RUN playwright install-deps

# Set user and folder
USER appuser
WORKDIR /home/appuser
RUN mkdir src

RUN playwright install chromium

# COPY ./ /home/appuser/src
EXPOSE 7999
WORKDIR /home/appuser/src
ENTRYPOINT [ "python", "main.py" ]
