{{- if and .Values.ha.enabled .Values.migrationState.completed }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress
  namespace: {{ .Values.ha.namespace }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ha.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ha-service
            port:
              number: 8123
{{- end }}