{{- if and .Values.ha.enabled .Values.migrationState.completed }}
apiVersion: v1
kind: Service
metadata:
  name: ha-service
  namespace: {{ .Values.ha.namespace }}
  labels:
    app.kubernetes.io/name: ha
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ha
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
{{- end }}