version: '3'

tasks:
  deploy:
    desc: Deploy the application by the helm chart
    cmds:
      - helm upgrade --install web helm-chart

  run:
    desc: Run the application from published image (for local testing)
    cmds:
      - |
        read -r -p "Docker image tag [latest/main/sha-]: " IMAGE_TAG
        IMAGE_TAG=${IMAGE_TAG:-main}
        docker run -i -p 8001:8001 --rm ghcr.io/yyyaaan/core/web:${IMAGE_TAG}

  test:
    desc: "run unit tests"
    cmds:
      - echo "Running unit tests pending implementation"
