apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-ingress
  namespace: {{ .Values.stirlingPdf.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth-oauth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.stirlingPdf.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdf-svc
            port:
              number: 80