namespace: web
certManager:
  enabled: true
  issuerName: letsencrypt-prod
authMiddleware:
  enabled: true
  name: auth-oauth@kubernetescrd
image:
  repository: yyyaaan/play
  tag: alpha1
  pullPolicy: IfNotPresent
envFromSecretList:
  - email-credentials
  - tz-config
hostPathForData: /Users/yyy/Lab/home/data/app
memDiskSize: 100Mi
service:
  targetPort: 7999
ingress:
  host: play.omop.fi
mailing:
  schedule: "39 9 * * *"
  timeZone: "Europe/Helsinki"