debugPod:
  enabled: false
# debugPod use ffmpeg configs and all jobs' volumes

# ffmpeg has init container, see manifest directly
ffmpeg:
  namespace: home-internal
  schedule: "3 1 * * *"
  timeZone: "Europe/Helsinki"
  image:
    repository: ghcr.io/yyyaaan/core/poller
    tag: "alpha1"
    pullPolicy: IfNotPresent
  envFromSecretList:
    - poller-credentials
    - tz-config
  hostPathMedia: /mnt/kingston/share/media
  resources:
    requests:
      cpu: "1000m"
      memory: "500Mi"
    limits:
      cpu: "2000m"
      memory: "3072Mi"

elenia:
  namespace: home-internal
  schedule: "2-59/15 * * * *"
  timezone: "Europe/Helsinki"
  image:
    repository: ghcr.io/yyyaaan/core/poller
    tag: "alpha1"
    pullPolicy: IfNotPresent
  envFromSecretList:
    - poller-credentials
    - tz-config
  hostPathMedia: /mnt/kingston/share/media
  hostPathForData: /mnt/kingston/home/data/app
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
    limits:
      cpu: "100m"
      memory: "200Mi"

