
# ffmpeg has init container, see manifest directly
ffmpeg:
  namespace: home-internal
  schedule: "3 1 * * *"
  timeZone: "Europe/Helsinki"
  image:
    repository: yyyaaan/poller
    tag: "alpha1"
    pullPolicy: IfNotPresent
  envFromSecretList:
    - poller-credentials
  hostPathMedia: /mnt/kingston/share/media
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  jobs:
    - name: elenia
      suspend: false
      schedule: "2-59/15 * * * *"
      command: 
        - "/usr/local/bin/python"
        - "/app/job_elenia.py"

elenia:
  namespace: home-internal
  schedule: "2-59/15 * * * *"
  timezone: "Europe/Helsinki"
  image:
    repository: yyyaaan/poller
    tag: "alpha1"
    pullPolicy: IfNotPresent
  command: 
    - "/usr/local/bin/python"
    - "/app/job_elenia.py"
  envFromSecretList:
    - poller-credentials
  hostPathMedia: /mnt/kingston/share/media
  hostPathForData: /mnt/kingston/home/data/app
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
    limits:
      cpu: "100m"
      memory: "200Mi"

